# URI
URI_DEFAULT = "/scral/v1.0/gps-tracker-gw"
URI_GPS_TAG_REGISTRATION = URI_DEFAULT + "/gps-tag"
URI_GPS_TAG_LOCALIZATION = URI_GPS_TAG_REGISTRATION + "/localization"
URI_GPS_TAG_ALERT = URI_GPS_TAG_REGISTRATION + "/alert"

# Port
VPN_PORT = 8260
