URI_DEFAULT = "/scral/v1.0/wristband-gw"
URI_WRISTBAND_ASSOCIATION = URI_DEFAULT + "/friend-connect"
URI_WRISTBAND_REGISTRATION = URI_DEFAULT + "/wearable"
URI_WRISTBAND_LOCALIZATION = URI_WRISTBAND_REGISTRATION + "/localization"
URI_WRISTBAND_BUTTON = URI_WRISTBAND_REGISTRATION + "/button"


PROPERTY_LOCALIZATION_NAME = "Localization-Wristband"
PROPERTY_BUTTON_NAME = "Button-Wristband"

SENSOR_ULTRAWIDEBAND_SCRAL = "UWB"
SENSOR_ULTRAWIDEBAND_DEXELS = "uwb"
